version: '3.3'
networks:
  redpanda_network:
    driver: bridge
services:
  # Redpanda cluster
  redpanda-1:
    image: docker.redpanda.com/vectorized/redpanda:v22.3.5
    container_name: redpanda-1
    networks:
      - redpanda_network
    command:
      - redpanda
      - start
      - --smp 1
      - --reserve-memory 0M
      - --overprovisioned
      - --node-id 1
      - --kafka-addr                 PLAINTEXT://redpanda-1:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr       PLAINTEXT://redpanda-1:29092,OUTSIDE://redpanda-1:9092
      - --pandaproxy-addr            PLAINTEXT://redpanda-1:28082,OUTSIDE://0.0.0.0:18082
      - --advertise-pandaproxy-addr  PLAINTEXT://redpanda-1:28082,OUTSIDE://redpanda-1:8082
      - --schema-registry-addr       PLAINTEXT://redpanda-1:8083,OUTSIDE://0.0.0.0:18083
      - --rpc-addr                   redpanda-1:33145
      - --advertise-rpc-addr         redpanda-1:33145
    ports:
      - 8083:8083
      - 8082:8082
      - 9092:9092
      - 28082:28082
      - 29092:29092
      - 19644:9644

  console:
    container_name: redpanda-console
    image: docker.redpanda.com/redpandadata/console:v2.3.1
    entrypoint: /bin/sh
    networks:
      - redpanda_network
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console'
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda-1:9092"]
          schemaRegistry:
            enabled: true
            urls: ["http://redpanda-1:8083"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda-1:9644"]
    ports:
      - 8080:8080
    depends_on:
      - redpanda-1

  # Flink cluster
  jobmanager:
    container_name: jobmanager
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    networks:
      - redpanda_network
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager        

  taskmanager:
    container_name: taskmanager
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - jobmanager
    networks:
      - redpanda_network
    command: taskmanager
    #scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 20
       
  sql-client:
    container_name: sql-client
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - redpanda_network
    command:
      - /opt/flink/bin/sql-client.sh
      - embedded
      - -l
      - /opt/sql-client/lib
    depends_on:
      - jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        rest.address: jobmanager
    volumes:
      - ./data/sql:/etc/sql

  opensky:
    build: opensky
    container_name: opensky
    networks:
      - redpanda_network
    depends_on:
      - redpanda-1
